export const users = [
  {
    id: "davi",
    name: "Davi Vanadio",
    role: "Administrador",
    email: "davi@canalho.com.br",
    phone: "(11) 99999-1000",
    registry: "CHO-ADM-01",
  },
  {
    id: "reginaldo",
    name: "Reginaldo Melo",
    role: "Gestor Técnico",
    email: "reginaldo@canalho.com.br",
    phone: "(11) 99999-2000",
    registry: "CHO-GT-04",
  },
  {
    id: "vitor",
    name: "Vitor Almeida",
    role: "Higienista",
    email: "vitor@canalho.com.br",
    phone: "(11) 99999-3000",
    registry: "CHO-HO-09",
  },
  {
    id: "cliente-exemplo",
    name: "Cliente Exemplo",
    role: "Usuário Cliente",
    email: "contato@clienteexemplo.com.br",
    phone: "(11) 99999-4000",
    registry: "CLI-02",
  },
];

export const customers = [
  {
    id: "acme",
    name: "ACME Indústria Química Ltda",
    type: "Jurídica",
    document: "12.345.678/0001-90",
    email: "contato@acme.com.br",
    phone: "(11) 3322-4000",
    contact: "Patrícia Campos",
    city: "Guarulhos/SP",
    addresses: [
      {
        label: "Matriz",
        zip: "07000-000",
        street: "Rod. Industrial, 421",
        district: "Cumbica",
        city: "Guarulhos",
        state: "SP",
      },
    ],
    notes: "Operação com solventes, estufa e área de expedição climatizada.",
    analyses: 6,
    quotations: 4,
    samplings: 8,
  },
  {
    id: "sao-bento",
    name: "Metalúrgica São Bento",
    type: "Jurídica",
    document: "41.225.678/0001-17",
    email: "qhse@saobento.com.br",
    phone: "(11) 3660-1840",
    contact: "Rafael Moura",
    city: "Sorocaba/SP",
    addresses: [
      {
        label: "Planta 1",
        zip: "18000-000",
        street: "Av. das Prensas, 850",
        district: "Distrito Industrial",
        city: "Sorocaba",
        state: "SP",
      },
    ],
    notes: "Linha de usinagem, pintura e manutenção mecânica.",
    analyses: 9,
    quotations: 5,
    samplings: 14,
  },
  {
    id: "nova-era",
    name: "Plásticos Nova Era",
    type: "Jurídica",
    document: "50.876.001/0001-22",
    email: "seguranca@novaera.com.br",
    phone: "(19) 3012-4490",
    contact: "Aline Sampaio",
    city: "Campinas/SP",
    addresses: [
      {
        label: "Fábrica",
        zip: "13000-000",
        street: "Rua das Resinas, 91",
        district: "Techno Park",
        city: "Campinas",
        state: "SP",
      },
    ],
    notes: "Extrusão, reciclagem e movimentação interna.",
    analyses: 4,
    quotations: 3,
    samplings: 5,
  },
  {
    id: "horizonte",
    name: "Farmacêutica Horizonte",
    type: "Jurídica",
    document: "67.901.444/0001-08",
    email: "ehs@horizonte.com.br",
    phone: "(21) 3888-9000",
    contact: "Juliana Freitas",
    city: "Duque de Caxias/RJ",
    addresses: [
      {
        label: "Unidade Rio",
        zip: "25000-000",
        street: "Av. Formulação, 712",
        district: "Polo Farmacêutico",
        city: "Duque de Caxias",
        state: "RJ",
      },
    ],
    notes: "Manipulação química controlada e salas limpas.",
    analyses: 5,
    quotations: 7,
    samplings: 10,
  },
  {
    id: "prefeitura",
    name: "Prefeitura Municipal Exemplo",
    type: "Jurídica",
    document: "46.111.002/0001-55",
    email: "saudeocupacional@prefeitura.gov.br",
    phone: "(31) 3999-8890",
    contact: "Carlos Vilela",
    city: "Belo Horizonte/MG",
    addresses: [
      {
        label: "Secretaria",
        zip: "30000-000",
        street: "Praça Central, 15",
        district: "Centro",
        city: "Belo Horizonte",
        state: "MG",
      },
    ],
    notes: "Contrato com múltiplas secretarias e equipes externas.",
    analyses: 8,
    quotations: 6,
    samplings: 12,
  },
];

export const agents = [
  {
    id: "tolueno",
    name: "Tolueno",
    type: "Químico",
    cas: "108-88-3",
    method: "NHO-05",
    rule: "NR-15",
    criticality: "Alta",
    price: "R$ 480",
    quantify: "Quantificar",
    recommendation:
      "Volatilidade alta em bancada aberta, sugerindo amostragem representativa da jornada.",
  },
  {
    id: "acetona",
    name: "Acetona",
    type: "Químico",
    cas: "67-64-1",
    method: "NIOSH 1300",
    rule: "eSocial",
    criticality: "Média",
    price: "R$ 420",
    quantify: "Quantificar",
    recommendation:
      "Exposição intermitente em limpeza de peças; manter validação humana da estratégia.",
  },
  {
    id: "benzeno",
    name: "Benzeno",
    type: "Químico",
    cas: "71-43-2",
    method: "NHO-05",
    rule: "LINACH",
    criticality: "Crítica",
    price: "R$ 650",
    quantify: "Quantificar",
    recommendation:
      "Agente com carcinogenicidade reconhecida, exigindo decisão técnica explícita.",
  },
  {
    id: "ruido",
    name: "Ruído",
    type: "Físico",
    cas: "",
    method: "NHO-01",
    rule: "NR-15",
    criticality: "Alta",
    price: "R$ 360",
    quantify: "Quantificar",
    recommendation:
      "Operação contínua em célula de corte com potencial acima de 85 dB(A).",
  },
  {
    id: "calor",
    name: "Calor",
    type: "Físico",
    cas: "",
    method: "NHO-06",
    rule: "NR-15",
    criticality: "Média",
    price: "R$ 390",
    quantify: "Avaliar",
    recommendation:
      "Área de forno com variação operacional ao longo dos turnos.",
  },
];

export const prhoAnalyses = [
  {
    id: "prho-2026-041",
    code: "PRHO 2026-041",
    customerId: "sao-bento",
    customer: "Metalúrgica São Bento",
    owner: "Reginaldo Melo",
    responsible: "Reginaldo Melo",
    sector: "Pintura e manutenção",
    statusCode: "approval_pending",
    documents: 6,
    extractedAgents: 9,
    pendingItems: 4,
    criticalPendingItems: 1,
    quantifiedAgents: 5,
    status: "Aprovação pendente",
    createdAt: "17 Jun 2026",
    updatedAt: "17 Jun 2026 19:20",
    analysisDate: "17 Jun 2026",
    objective: "Revisar agentes de pintura e manutenção.",
    title: "APR HO Pintura e manutenção 2026",
    creditStatus: "Atenção",
    confidence: 82,
    nextAction: "Concluir aprovação técnica",
    version: "v0.9",
  },
  {
    id: "prho-2026-038",
    code: "PRHO 2026-038",
    customerId: "acme",
    customer: "ACME Indústria Química Ltda",
    owner: "Vitor Almeida",
    responsible: "Vitor Almeida",
    sector: "Desengraxe e expedição",
    statusCode: "classification_pending",
    documents: 4,
    extractedAgents: 6,
    pendingItems: 2,
    criticalPendingItems: 0,
    quantifiedAgents: 3,
    status: "Classificação pendente",
    createdAt: "15 Jun 2026",
    updatedAt: "16 Jun 2026 09:15",
    objective: "Atualizar inventário de solventes.",
    title: "APR HO Solventes e expedição",
    creditStatus: "Regular",
    confidence: 89,
    nextAction: "Classificar tecnicamente",
    version: "v0.7",
  },
  {
    id: "prho-2026-033",
    code: "PRHO 2026-033",
    customerId: "horizonte",
    customer: "Farmacêutica Horizonte",
    owner: "Davi Vanadio",
    responsible: "Davi Vanadio",
    sector: "Manipulação encapsulada",
    statusCode: "budget_generated",
    documents: 8,
    extractedAgents: 12,
    pendingItems: 0,
    criticalPendingItems: 0,
    quantifiedAgents: 7,
    status: "Pré-orçamento gerado",
    createdAt: "09 Jun 2026",
    updatedAt: "12 Jun 2026 14:02",
    objective: "Nova linha de manipulação encapsulada.",
    title: "APR HO Linha encapsulada",
    creditStatus: "Regular",
    confidence: 91,
    nextAction: "Revisar pré-orçamento",
    version: "v1.0",
  },
];

export const prhoReviewAgents = [
  {
    id: "rv-01",
    name: "Tolueno",
    type: "Químico",
    agentType: "Químico",
    cas: "108-88-3",
    reference: "CAS 108-88-3",
    concentration: "20",
    intensity: "20",
    unit: "ppm",
    state: "Líquido volátil",
    physicalState: "Líquido volátil",
    sector: "Pintura",
    role: "Pintor industrial",
    workerFunction: "Pintor industrial",
    ghe: "GHE-07",
    method: "NIOSH 1501",
    source: "FISPQ Atlas Solv 03/2026",
    sourceDocumentId: "doc-01",
    sourcePage: "p. 7",
    confidence: 86,
    decision: "Quantificar",
    technicalDecision: "Quantificar",
    reviewStatus: "Aprovado",
    aihaCategory: "Categoria 2",
    frequency: "Semestral",
    nr15Annex: "Anexo 11",
    nr15Limit: "78 ppm",
    acgihTwa: "20 ppm",
    acgihStel: "Não aplicável",
    nioshTwa: "100 ppm",
    nhoReference: "Não aplicável",
    linachStatus: "Não listado",
    esocialCode: "01.01.001",
    decretoCode: "1.0.19",
    targetOrgan: "Sistema nervoso central",
    sourceExcerpt: "Limite de exposição ocupacional TWA: 20 ppm.",
    risk: "Alta",
    justification:
      "Concentração citada e ausência de enclausuramento indicam necessidade de medição.",
    observation:
      "Método sugerido pela IA, pendente apenas de conferência final do plano amostral.",
    pendingTypes: [],
    statusLabel: "Revisado",
  },
  {
    id: "rv-02",
    name: "Ruído contínuo",
    type: "Físico",
    agentType: "Físico",
    cas: "NHO-01",
    reference: "NHO-01 / NR-15 Anexo 1",
    concentration: "85",
    intensity: "85",
    unit: "dB(A)",
    state: "Onda sonora contínua",
    physicalState: "Onda sonora contínua",
    sector: "Corte",
    role: "Operador de serra",
    workerFunction: "Operador de serra",
    ghe: "GHE-03",
    method: "NHO-01",
    source: "Laudo histórico 2024",
    sourceDocumentId: "doc-02",
    sourcePage: "p. 5",
    confidence: 73,
    decision: "Avaliação manual necessária",
    technicalDecision: "Avaliação manual necessária",
    reviewStatus: "Corrigido",
    aihaCategory: "Categoria 2",
    frequency: "Semestral",
    nr15Annex: "Anexo 1",
    nr15Limit: "85 dB(A)",
    acgihTwa: "Não aplicável",
    acgihStel: "Não aplicável",
    nioshTwa: "85 dB(A)",
    nhoReference: "NHO-01",
    linachStatus: "Não aplicável",
    esocialCode: "02.01.014",
    decretoCode: "2.0.01",
    targetOrgan: "Sistema auditivo",
    sourceExcerpt: "Ruído contínuo entre 82 e 88 dB(A).",
    risk: "Alta",
    justification:
      "Ruído requer cruzamento com NR-15, NHO-01, Decreto 3048/99 e eSocial antes da aprovação.",
    observation:
      "Falta validar jornada, dose e cenário operacional atual para confirmar periodicidade.",
    pendingTypes: ["normative_conflict"],
    statusLabel: "Pendente de conferência",
  },
  {
    id: "rv-03",
    name: "Benzeno",
    type: "Químico",
    agentType: "Químico",
    cas: "",
    reference: "Composição protegida",
    concentration: "Segredo industrial",
    intensity: "Segredo industrial",
    unit: "%",
    state: "Vapor orgânico",
    physicalState: "Vapor orgânico",
    sector: "",
    role: "",
    workerFunction: "",
    ghe: "",
    method: "Sugerido pela IA",
    source: "FDS Solvente Premium 04/2026",
    sourceDocumentId: "doc-04",
    sourcePage: "p. 3",
    confidence: 49,
    decision: "Dados insuficientes",
    technicalDecision: "Dados insuficientes",
    reviewStatus: "Pendente",
    aihaCategory: "Categoria 1",
    frequency: "Trimestral",
    nr15Annex: "Anexo 13-A",
    nr15Limit: "Conforme atividade",
    acgihTwa: "0,5 ppm",
    acgihStel: "2,5 ppm",
    nioshTwa: "0,1 ppm",
    nhoReference: "Não aplicável",
    linachStatus: "Grupo 1 / carcinogênico",
    esocialCode: "01.01.002",
    decretoCode: "1.0.01",
    targetOrgan: "Medula óssea",
    sourceExcerpt:
      "Composição protegida por segredo industrial. Hidrocarbonetos aromáticos presentes.",
    risk: "Crítica",
    justification:
      "Agente potencialmente carcinogênico com segredo industrial; a linha não pode ser aprovada automaticamente.",
    observation:
      "Solicitar informação complementar ao fabricante ou justificar tecnicamente a continuidade.",
    pendingTypes: ["industrial_secret", "missing_cas", "missing_sector_function"],
    statusLabel: "Bloqueado",
  },
  {
    id: "rv-04",
    name: "Calor IBUTG",
    type: "Físico",
    agentType: "Físico",
    cas: "IBUTG",
    reference: "IBUTG / NR-15 Anexo 3",
    concentration: "26,8",
    intensity: "26,8",
    unit: "°C IBUTG",
    state: "Energia térmica",
    physicalState: "Energia térmica",
    sector: "Forno",
    role: "Operador de forno",
    workerFunction: "Operador de forno",
    ghe: "GHE-09",
    method: "NHO-06",
    source: "Relatório térmico 2025",
    sourceDocumentId: "doc-05",
    sourcePage: "p. 11",
    confidence: 68,
    decision: "Solicitar informação complementar",
    technicalDecision: "Solicitar informação complementar",
    reviewStatus: "Corrigido",
    aihaCategory: "Categoria 2",
    frequency: "Semestral",
    nr15Annex: "Anexo 3",
    nr15Limit: "Depende de leve/moderada/pesada",
    acgihTwa: "Não aplicável",
    acgihStel: "Não aplicável",
    nioshTwa: "Não aplicável",
    nhoReference: "NHO-06",
    linachStatus: "Não aplicável",
    esocialCode: "02.01.016",
    decretoCode: "2.0.07",
    targetOrgan: "Sistema termorregulador",
    sourceExcerpt: "IBUTG 26,8 em rotina de forno. Sem regime de pausa descrito.",
    risk: "Alta",
    justification:
      "Sem atividade metabólica e regime de trabalho/descanso, o enquadramento térmico ainda está incompleto.",
    observation:
      "Preencher leve/moderada/pesada e condições do local de descanso na revisão humana.",
    pendingTypes: ["manual_review_required"],
    statusLabel: "Pendente de complemento",
  },
];

export const documents = [
  {
    id: "doc-01",
    name: "FISPQ_TOLUENO_ATLAS.pdf",
    kind: "FISPQ / FDS",
    detectedType: "FDS/FISPQ",
    type: "PDF",
    status: "Extração concluída",
    extension: ".pdf",
    pages: 18,
    sheets: 0,
    confidence: 91,
    note: "Versão 03/2026 • 18 páginas • CAS e limites localizados",
    alert: "",
    preview: '"Limite de exposição ocupacional TWA: 20 ppm. Produto inflamável."',
  },
  {
    id: "doc-02",
    name: "laudo_pintura_2024.pdf",
    kind: "Laudo técnico",
    detectedType: "Relatório de medição",
    type: "PDF",
    status: "Revisão necessária",
    extension: ".pdf",
    pages: 12,
    sheets: 0,
    confidence: 73,
    note: "Medições históricas • ruído contínuo e calor em forno",
    alert: "Divergência normativa em ruído contínuo",
    preview: '"Ruído contínuo entre 82 e 88 dB(A). Recomenda-se nova campanha."',
  },
  {
    id: "doc-03",
    name: "inventario_agentes.xlsx",
    kind: "Planilha PRHO/APR",
    detectedType: "Planilha PRHO/APR",
    type: "XLSX",
    status: "Aguardando processamento",
    extension: ".xlsx",
    pages: 0,
    sheets: 3,
    confidence: 64,
    note: "Base interna do cliente • 3 abas mapeadas",
    alert: "",
    preview: '"Linha A: Solvente, desengraxe, manutenção. Linha B: ruído de corte."',
  },
  {
    id: "doc-04",
    name: "FDS_SOLVENTE_PREMIUM.docx",
    kind: "FISPQ / FDS",
    detectedType: "FDS/FISPQ",
    type: "DOCX",
    status: "Documento não reconhecido",
    extension: ".docx",
    pages: 9,
    sheets: 0,
    confidence: 49,
    note: "Composição protegida por segredo industrial",
    alert: "Segredo industrial encontrado",
    preview: '"Composição protegida por segredo industrial. Hidrocarbonetos aromáticos presentes."',
  },
  {
    id: "doc-05",
    name: "relatorio_termico_forno.pdf",
    kind: "Relatório de medição",
    detectedType: "Relatório de medição",
    type: "PDF",
    status: "Lendo arquivo",
    extension: ".pdf",
    pages: 14,
    sheets: 0,
    confidence: 68,
    note: "IBUTG e atividade térmica do forno principal",
    alert: "Regime de trabalho/descanso ausente",
    preview: '"IBUTG 26,8. Atividade e pausas não identificadas no corpo do laudo."',
  },
  {
    id: "doc-06",
    name: "fotos_area_pintura.zip",
    kind: "Imagem",
    detectedType: "Imagem",
    type: "PNG/JPG",
    status: "Documento ilegível",
    extension: ".zip",
    pages: 0,
    sheets: 0,
    confidence: 32,
    note: "OCR com baixa confiança em 4 arquivos",
    alert: "Imagens desfocadas",
    preview: '"Tabela cortada, sem unidade rastreável para o valor destacado na imagem."',
  },
];

export const prhoPendingItems = [
  {
    id: "pen-01",
    agentId: "rv-02",
    type: "normative_conflict",
    severity: "Alta",
    title: "Ruído sem amarração normativa completa",
    description:
      "Cruzar NR-15 Anexo 1, NHO-01, Decreto 3048/99 e eSocial antes da classificação final.",
    status: "Aberta",
  },
  {
    id: "pen-02",
    agentId: "rv-03",
    type: "industrial_secret",
    severity: "Crítica",
    title: "Segredo industrial encontrado",
    description:
      "Composição protegida por segredo industrial. Solicitar complemento ou justificar tecnicamente.",
    status: "Aberta",
  },
  {
    id: "pen-03",
    agentId: "rv-03",
    type: "missing_cas",
    severity: "Alta",
    title: "CAS ausente para agente químico",
    description: "Não inventar CAS. Manter pendência até encontrar fonte válida.",
    status: "Aberta",
  },
  {
    id: "pen-04",
    agentId: "rv-04",
    type: "manual_review_required",
    severity: "Média",
    title: "Calor sem regime de trabalho/descanso",
    description:
      "Registrar atividade leve/moderada/pesada e condições do local de descanso.",
    status: "Aberta",
  },
];

export const prhoBudgetItems = [
  {
    id: "bud-01",
    agentId: "rv-01",
    description: "Amostragem de Tolueno - setor pintura",
    type: "Químico",
    sector: "Pintura",
    role: "Pintor industrial",
    ghe: "GHE-07",
    method: "NIOSH 1501",
    frequency: "Semestral",
    quantity: 2,
    unitPrice: "R$ 480",
    totalPrice: "R$ 960",
    status: "Selecionado",
    observation: "Incluir cadeia de custódia e bomba de amostragem.",
  },
  {
    id: "bud-02",
    agentId: "rv-02",
    description: "Dosimetria de ruído contínuo - setor corte",
    type: "Físico",
    sector: "Corte",
    role: "Operador de serra",
    ghe: "GHE-03",
    method: "NHO-01",
    frequency: "Semestral",
    quantity: 1,
    unitPrice: "R$ 360",
    totalPrice: "R$ 360",
    status: "Pendente",
    observation: "Liberar somente após validação normativa final.",
  },
  {
    id: "bud-03",
    agentId: "rv-04",
    description: "Avaliação térmica IBUTG - área de forno",
    type: "Físico",
    sector: "Forno",
    role: "Operador de forno",
    ghe: "GHE-09",
    method: "NHO-06",
    frequency: "Semestral",
    quantity: 1,
    unitPrice: "R$ 420",
    totalPrice: "R$ 420",
    status: "Selecionado",
    observation: "Revisar regime de pausa antes do fechamento comercial.",
  },
];

export const preQuotations = [
  {
    id: "pre-041",
    customer: "Metalúrgica São Bento",
    origin: "PRHO 2026-041",
    status: "Pronto para orçamento",
    totalAgents: 9,
    selectedAgents: 5,
    date: "17 Jun 2026",
    value: "R$ 5.480",
  },
  {
    id: "pre-038",
    customer: "ACME Indústria Química Ltda",
    origin: "PRHO 2026-038",
    status: "Em revisão",
    totalAgents: 6,
    selectedAgents: 3,
    date: "16 Jun 2026",
    value: "R$ 3.240",
  },
];

export const quotations = [
  {
    id: "orc-2061",
    number: "ORC-2061",
    customer: "Metalúrgica São Bento",
    status: "Pendente",
    total: "R$ 8.960",
    validity: "30 dias",
    email: "Enviado",
    whatsapp: "Pendente",
    date: "17 Jun 2026",
  },
  {
    id: "orc-2054",
    number: "ORC-2054",
    customer: "Farmacêutica Horizonte",
    status: "Aprovado",
    total: "R$ 14.200",
    validity: "20 dias",
    email: "Enviado",
    whatsapp: "Enviado",
    date: "11 Jun 2026",
  },
  {
    id: "orc-2051",
    number: "ORC-2051",
    customer: "ACME Indústria Química Ltda",
    status: "Rascunho",
    total: "R$ 5.720",
    validity: "15 dias",
    email: "Não enviado",
    whatsapp: "Não enviado",
    date: "09 Jun 2026",
  },
];

export const quotationItems = [
  {
    id: "item-01",
    evaluation: "Amostragem pessoal",
    agent: "Tolueno",
    sector: "Pintura",
    role: "Pintor industrial",
    exposure: "Intermitente",
    quantity: 2,
    unitPrice: "R$ 480",
    total: "R$ 960",
  },
  {
    id: "item-02",
    evaluation: "Dosimetria",
    agent: "Ruído",
    sector: "Corte",
    role: "Operador de serra",
    exposure: "Contínua",
    quantity: 3,
    unitPrice: "R$ 360",
    total: "R$ 1.080",
  },
  {
    id: "item-03",
    evaluation: "Amostragem área",
    agent: "Acetona",
    sector: "Lavagem",
    role: "Auxiliar",
    exposure: "Eventual",
    quantity: 1,
    unitPrice: "R$ 420",
    total: "R$ 420",
  },
];

export const samplingPlans = [
  {
    id: "sam-9001",
    quotationId: "orc-2054",
    customer: "Farmacêutica Horizonte",
    agent: "Benzeno",
    type: "Químico",
    sector: "Manipulação",
    role: "Operador de processo",
    employee: "Leandro Costa",
    status: "Em campo",
    owner: "Vitor Almeida",
    dueDate: "20 Jun 2026",
  },
  {
    id: "sam-9002",
    quotationId: "orc-2061",
    customer: "Metalúrgica São Bento",
    agent: "Ruído",
    type: "Ruído",
    sector: "Corte",
    role: "Operador de serra",
    employee: "Bruno Telles",
    status: "Planejada",
    owner: "Reginaldo Melo",
    dueDate: "22 Jun 2026",
  },
  {
    id: "sam-9003",
    quotationId: "orc-2061",
    customer: "Metalúrgica São Bento",
    agent: "Tolueno",
    type: "Químico",
    sector: "Pintura",
    role: "Pintor industrial",
    employee: "Marcelo Dias",
    status: "Aguardando resultado",
    owner: "Vitor Almeida",
    dueDate: "24 Jun 2026",
  },
];

export const labImports = [
  {
    id: "lab-210",
    laboratory: "Lab HO Sudeste",
    sample: "sam-9003",
    customer: "Metalúrgica São Bento",
    status: "Em revisão",
    detected: "Tolueno 18,6 ppm",
    updatedAt: "17 Jun 2026 18:40",
  },
  {
    id: "lab-206",
    laboratory: "Lab Aero",
    sample: "sam-9001",
    customer: "Farmacêutica Horizonte",
    status: "Concluída",
    detected: "Benzeno não detectado",
    updatedAt: "15 Jun 2026 11:10",
  },
];

export const reports = [
  {
    id: "rel-013",
    code: "CHO-REL-2026-013",
    customer: "Metalúrgica São Bento",
    status: "Em revisão",
    source: "ORC-2061",
    version: "v0.8",
    updatedAt: "17 Jun 2026 19:35",
  },
  {
    id: "rel-010",
    code: "CHO-REL-2026-010",
    customer: "Farmacêutica Horizonte",
    status: "Concluída",
    source: "ORC-2054",
    version: "v1.0",
    updatedAt: "13 Jun 2026 15:00",
  },
];

export const services = [
  { id: "srv-01", name: "Amostragem química", owner: "Operações", price: "R$ 480" },
  { id: "srv-02", name: "Dosimetria de ruído", owner: "Operações", price: "R$ 360" },
  { id: "srv-03", name: "Relatório técnico", owner: "Engenharia", price: "R$ 780" },
];

export const costs = [
  { id: "cost-01", name: "Deslocamento regional", category: "Logística", price: "R$ 290" },
  { id: "cost-02", name: "Frete de bomba", category: "Equipamentos", price: "R$ 120" },
  { id: "cost-03", name: "Taxa laboratorial", category: "Laboratório", price: "R$ 210" },
];

export const equipments = [
  { id: "eq-01", name: "Bomba SKC 224", status: "Disponível", calibration: "Ago/2026" },
  { id: "eq-02", name: "Dosímetro Quest Edge", status: "Em campo", calibration: "Jul/2026" },
  { id: "eq-03", name: "Termômetro de globo", status: "Reserva", calibration: "Set/2026" },
];

export const plans = [
  {
    id: "starter",
    name: "Starter",
    price: "R$ 1.490/mês",
    features: [
      "1 workspace",
      "Até 20 análises PRHO/mês",
      "Importação de laudos opcional",
    ],
  },
  {
    id: "professional",
    name: "Professional",
    price: "R$ 2.990/mês",
    features: [
      "3 workspaces",
      "80 análises PRHO/mês",
      "Pré-orçamento e orçamento completo",
    ],
  },
  {
    id: "business",
    name: "Business",
    price: "R$ 5.490/mês",
    features: [
      "10 workspaces",
      "Uso ampliado de IA",
      "Fluxo completo até relatório final",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: "Sob consulta",
    features: [
      "SSO e governança",
      "Módulos sob medida",
      "Onboarding dedicado",
    ],
  },
];

export const usageMetrics = [
  { id: "ai", label: "Créditos de IA", used: 620, total: 1000, unit: "" },
  { id: "prho", label: "Análises PRHO", used: 48, total: 80, unit: "" },
  { id: "storage", label: "Armazenamento", used: 72, total: 100, unit: " GB" },
];

export const reportSections = [
  {
    title: "Caracterização do ambiente",
    copy:
      "Resumo das atividades, setores, jornadas, agentes identificados e base documental consolidada.",
  },
  {
    title: "Resultados analíticos",
    copy:
      "Integração entre memória de campo, laudos laboratoriais e interpretação técnica validada.",
  },
  {
    title: "Conclusão e recomendações",
    copy:
      "Conclusão formal com recomendações de controle, pendências e anexos obrigatórios.",
  },
];
